src/App/Models/Oferta/RegisterViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace App.Models.Oferta
{
    public class RegisterViewModel
    {
        public RegisterViewModel() 
        {
            this.Countries = new List<SelectListItem>
            {
                new SelectListItem { Text = "Argentina", Value = "Argentina" },
                new SelectListItem { Text = "Bolivia", Value = "Bolivia" },
                new SelectListItem { Text = "Brasil", Value = "Brasil" },
                new SelectListItem { Text = "Canadá", Value = "Canadá" },
                new SelectListItem { Text = "Chile", Value = "Chile" },
                new SelectListItem { Text = "Colombia", Value = "Colombia" },
                new SelectListItem { Text = "Costa Rica", Value = "Costa Rica" },
                new SelectListItem { Text = "Cuba", Value = "Cuba" },
                new SelectListItem { Text = "Ecuador", Value = "Ecuador" },
                new SelectListItem { Text = "EEEUU", Value = "EEEUU" },
                new SelectListItem { Text = "El Salvador", Value = "El Salvador" },
                new SelectListItem { Text = "España", Value = "España" },
                new SelectListItem { Text = "Honduras", Value = "Honduras" },
                new SelectListItem { Text = "México", Value = "México" },
                new SelectListItem { Text = "Nicaragua", Value = "Nicaragua" },
                new SelectListItem { Text = "Panamá", Value = "Panamá" },
                new SelectListItem { Text = "Paraguay", Value = "Paraguay" },
                new SelectListItem { Text = "Perú", Value = "Perú" },
                new SelectListItem { Text = "Uruguay", Value = "Uruguay" },
                new SelectListItem { Text = "Venezuela", Value = "Venezuela" },
                new SelectListItem { Text = "Otro", Value = "Otro" }
            };

            this.Months = new List<SelectListItem>
            {
                new SelectListItem { Text = "Enero", Value = "Enero" },
                new SelectListItem { Text = "Febrero", Value = "Febrero" },
                new SelectListItem { Text = "Marzo", Value = "Marzo" },
                new SelectListItem { Text = "Abril", Value = "Abril" },
                new SelectListItem { Text = "Mayo", Value = "Mayo" },
                new SelectListItem { Text = "Junio", Value = "Junio" },
                new SelectListItem { Text = "Julio", Value = "Julio" },
                new SelectListItem { Text = "Agosto", Value = "Agosto" },
                new SelectListItem { Text = "Septiembre", Value = "Septiembre" },
                new SelectListItem { Text = "Octubre", Value = "Octubre" },
                new SelectListItem { Text = "Noviembre", Value = "Noviembre" },
                new SelectListItem { Text = "Diciembre", Value = "Diciembre" },
            };
        }

        public int CategoryId { get; set; }
        public int SurveyCompletionId { get; set; }

        //[Required]
        [Display(Name = "Nombre")]
        public string CompanyName { get; set; }
        
        //[Required]
        [Display(Name = "Descripción")]
        public string CompanyDescription { get; set; }

        //[Required]
        [Display(Name = "Sitio web")]
        public string CompanyWebSite { get; set; }

        public List<SelectListItem> Countries { get; set; }

        //[Required]
        [Display(Name = "País")]
        public string CompanyCountry { get; set; }

        //[Required]
        [Display(Name = "Ciudad")]
        public string CompanyCity { get; set; }

        //[Required]
        [Display(Name = "Dirección")]
        public string CompanyAddress { get; set; }

        [Display(Name = "Código Postal")]
        public string CompanyPostalCode { get; set; }

        [Display(Name = "Sucursales en")]
        public string CompanyBranchOfficesIn { get; set; }

        public List<SelectListItem> Months { get; set; }

        //[Required]
        [Display(Name = "Mes de inicio del año fiscal")]
        public string CompanyFiscalStartDate { get; set; }

        //[Required]
        [Display(Name = "Mes de cierre del año fiscal")]
        public string CompanyFiscalEndDate { get; set; }

        //[Required]
        [Display(Name = "Personal total de la empresa")]
        public int CompanyPeopleInCompany { get; set; }

        [Display(Name = "Logo")]
        public HttpPostedFileBase CompanyLogo { get; set; }

        public string CompanyLogoFileName { get; set; }

        //[Required]
        [Display(Name = "Nombre")]
        public string ProductName { get; set; }

        [Display(Name = "Version")]
        public string ProductVersion { get; set; }

        //[Required]
        [Display(Name = "Descripción")]
        public string ProductDescription { get; set; }

        [Display(Name = "Sitio web")]
        public string ProductWebSite { get; set; }

        //[Required]
        [Display(Name = "Nombre y Apellido")]
        public string ComercialContactFullName { get; set; }

        //[Required]
        [Display(Name = "Cargo / Función")]
        public string ComercialContactPosition { get; set; }

        //[Required]
        [Display(Name = "Teléfono")]
        public string ComercialContactPhone { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        public string ComercialContactEmail { get; set; }

        [Display(Name = "Nombre y Apellido")]
        public string ProductContactFullName { get; set; }

        [Display(Name = "Cargo / Función")]
        public string ProductContactPosition { get; set; }

        [Display(Name = "Teléfono")]
        public string ProductContactPhone { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        public string ProductContactEmail { get; set; }
    }
}

src/App/Models/Oferta/Survey/CategoryViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace App.Models.Oferta.Survey
{
    public class CategoryViewModel
    {
        public CategoryViewModel() 
        {
            this.Categories = new List<System.Web.Mvc.SelectListItem>();
        }

        [Required(ErrorMessage = "Por favor seleccione el rubro")]
        [Display(Name = "Rubro")]
        public string Category { get; set; }

        public List<System.Web.Mvc.SelectListItem> Categories { get; set; }
    }
}

src/App/Models/Oferta/TxtUserValidation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace App.Models.Oferta
{
    public class TxtUserValidation
    {
    }
}

src/App/Controllers/HomeController.cs
using App.Model.User;
using Model.Context;
using Model.Suvery;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace App.Controllers
{
    public class HomeController : Controller
    {
        private const int MaxValuePerAnswer = 10;
        private ModelContext modelContext;
        private IEnumerable<ApplicationUser> users;
        private IEnumerable<Survey> surveys;

        public HomeController()
        {
            this.modelContext = new ModelContext();
        }

        public ActionResult Index()
        {
            this.users = modelContext.Users.ToList();
            this.surveys = modelContext.Surveys.ToList();

            if (User.IsInRole("Oferta"))
                return RedirectToAction("Home", "Oferta");
            else
                return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/App/Controllers/Oferta/OfertaSurveyController.cs
using App.Attribute;
using App.DTO;
using App.Model.User;
using App.Models;
using App.Models.Survey;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Model.Context;
using Model.Model.Customer;
using Model.SurveyCompletion;
using Model.Suvery;
using Services;
using Services.Service.EmailService;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace App.Controllers.Oferta
{
    [MyAuthorize(Roles = "Oferta")]
    public class OfertaSurveyController : Controller
    {
        private ModelContext modelContext;
        private SurveyPartialCompletionBySupplyEmailService surveyPartialCompletionBySupplyEmailService;
        private SurveyCompletionBySupplyEmailService surveyCompletionBySupplyEmailService;
        private PdfService pdfService;
        public UserManager<ApplicationUser> userManager;
        public RoleManager<ApplicationRole> roleManager;

        public OfertaSurveyController()
        {
            this.modelContext = new ModelContext();
            this.surveyPartialCompletionBySupplyEmailService = new SurveyPartialCompletionBySupplyEmailService();
            this.surveyCompletionBySupplyEmailService = new SurveyCompletionBySupplyEmailService();
            this.pdfService = new PdfService();

            var userStore = new UserStore<ApplicationUser>(this.modelContext);
            var roleStore = new RoleStore<ApplicationRole>(this.modelContext);

            this.userManager = new UserManager<ApplicationUser>(userStore);
            this.roleManager = new RoleManager<ApplicationRole>(roleStore);
        }

        public ActionResult Index()
        {
            var categories = this.modelContext
                .Categories
                .Where(x => x.parentCategory == null)
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
                .ToList();

            var categoryViewModel = new App.Models.Oferta.Survey.CategoryViewModel
            {
                Categories = categories
            };

            return View("~/Views/Oferta/Survey/Category.cshtml", categoryViewModel);
        }

        [HttpGet]
        public ActionResult Register(int Category)
        {
            var model = new App.Models.Oferta.RegisterViewModel { CategoryId = Category };
            ViewBag.Argument = "Register";
            return View("~/Views/Oferta/Register.cshtml", model);
        }

        [HttpGet]
        public ActionResult RegisterContinue(int surveyCompletionId, string partialSaveKey)
        {
            var surveyCompletionParent = this.modelContext
                .SurveyCompletionParent
                .Include("Category")
                .Include("Company")
                .Include("Company.ComercialContact")
                .Include("Product")
                .Include("Product.ProductContact")
                .FirstOrDefault(x =>
                    x.Id == surveyCompletionId &&
                    x.PartialSaveKey == partialSaveKey &&
                    x.DeletedAt == null);

            if (surveyCompletionParent == null)
            {
                throw new ArgumentException("No se encuentra la evaluación");
            }

            var model = this.CompanyRegisterViewModelMap(surveyCompletionParent, surveyCompletionId);
            model.CategoryId = surveyCompletionParent.Category.Id;
            model.CompanyLogoFileName = surveyCompletionParent.Company.CompanyLogo;

            ViewBag.Argument = "RegisterContinue";

            return View("~/Views/Oferta/Register.cshtml", model);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Register")]
        public ActionResult Register(int Category, App.Models.Oferta.RegisterViewModel model, string Argument)
        {
            this.ValidateRegistration(model, false);

            if (!ModelState.IsValid)
            {
                ViewBag.Argument = Argument;
                return View("~/Views/Oferta/Register.cshtml", model);
            }

            var surveycomplation = this.RegisterViewModelCompanyMap(model);

            this.modelContext.Companies.Add(surveycomplation.Company);
            this.modelContext.Products.Add(surveycomplation.Product);
            this.modelContext.Contacts.Add(surveycomplation.Company.ComercialContact);
            this.modelContext.Contacts.Add(surveycomplation.Product.ProductContact);
            this.modelContext.SaveChanges();

            if (model.CompanyLogo != null)
            {
                surveycomplation.Company.CompanyLogo = surveycomplation.Company.Id + "_" + model.CompanyLogo.FileName;
            }

            this.modelContext.SaveChanges();

            if (model.CompanyLogo != null)
            {
                var fileName = Path.GetFileName(surveycomplation.Company.CompanyLogo);
                var path = Path.Combine(Server.MapPath("~/Content/images/logos"), fileName);
                model.CompanyLogo.SaveAs(path);
            }

            return RedirectToAction("Survey", "../Product", new { Category = Category, Company = surveycomplation.Company.Id });
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "RegisterPartial")]
        public ActionResult RegisterPartial(App.Models.Oferta.RegisterViewModel model, string Argument)
        {
            this.ValidateRegistration(model, true);

            if (!ModelState.IsValid)
            {
                ViewBag.Argument = Argument;
                return View("~/Views/Oferta/Register.cshtml", model);
            }

            var surveyCompletionTmp = this.RegisterViewModelCompanyMap(model);

            this.modelContext.Companies.Add(surveyCompletionTmp.Company);
            this.modelContext.Products.Add(surveyCompletionTmp.Product);
            this.modelContext.Contacts.Add(surveyCompletionTmp.Company.ComercialContact);
            this.modelContext.Contacts.Add(surveyCompletionTmp.Product.ProductContact);
            this.modelContext.SaveChanges();

            if (model.CompanyLogo != null)
            {
                surveyCompletionTmp.Company.CompanyLogo = surveyCompletionTmp.Company.Id + "_" + model.CompanyLogo.FileName;
            }

            this.modelContext.SaveChanges();

            if (model.CompanyLogo != null)
            {
                var fileName = Path.GetFileName(surveyCompletionTmp.Company.CompanyLogo);
                var path = Path.Combine(Server.MapPath("~/Content/images/logos"), fileName);
                model.CompanyLogo.SaveAs(path);
            }
            else
            {
                if (model.SurveyCompletionId != 0)
                {
                    var surveyCompletionPartialCompany = this.modelContext
                    .SurveysCompletion
                    .Include("Company")
                    .FirstOrDefault(x => x.Id == model.SurveyCompletionId)
                    .Company;

                    surveyCompletionTmp.Company.CompanyLogo = surveyCompletionPartialCompany.CompanyLogo;

                    this.modelContext.SaveChanges();
                }
            }

            var surveyViewModel = new SurveyViewModel
            {
                CompanyId = surveyCompletionTmp.Company.Id,
                CategoryId = model.CategoryId
            };

            var surveyCompletion = this.InsertSurveyCompletion(surveyViewModel, true);

            var template = this.RenderRazorViewToString("~/Views/Demanda/Email/EvaluationTemplate.cshtml", surveyCompletion);
            var pdfFileName = this.pdfService.GetEvaluationFileName(surveyCompletion.Id);
            var pdfFullName = this.pdfService.Generate(surveyCompletion.Id, template, pdfFileName);

            this.surveyPartialCompletionBySupplyEmailService.Send(pdfFullName, surveyCompletion);

            return RedirectToAction("ThanksPartial", "../Product/Evaluation");
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "RegisterContinue")]
        public ActionResult RegisterContinue(App.Models.Oferta.RegisterViewModel model, string Argument)
        {
            this.ValidateRegistration(model, false);

            if (!ModelState.IsValid)
            {
                ViewBag.Argument = Argument;
                return View("~/Views/Oferta/Register.cshtml", model);
            }

            var surveyCompletion = this.RegisterViewModelCompanyMap(model);

            this.modelContext.Companies.Add(surveyCompletion.Company);
            this.modelContext.Products.Add(surveyCompletion.Product);
            this.modelContext.Contacts.Add(surveyCompletion.Company.ComercialContact);
            this.modelContext.Contacts.Add(surveyCompletion.Product.ProductContact);
            this.modelContext.SaveChanges();

            if (model.CompanyLogo != null)
            {
                surveyCompletion.Company.CompanyLogo = surveyCompletion.Company.Id + "_" + model.CompanyLogo.FileName;
            }

            this.modelContext.SaveChanges();

            if (model.CompanyLogo != null)
            {
                var fileName = Path.GetFileName(surveyCompletion.Company.CompanyLogo);
                var path = Path.Combine(Server.MapPath("~/Content/images/logos"), fileName);
                model.CompanyLogo.SaveAs(path);
            }
            else
            {
                var surveyCompletionPartialCompany = this.modelContext
                    .SurveysCompletion
                    .Include("Company")
                    .FirstOrDefault(x => x.Id == model.SurveyCompletionId)
                    .Company;

                surveyCompletion.Company.CompanyLogo = surveyCompletionPartialCompany.CompanyLogo;

                this.modelContext.SaveChanges();
            }

            return RedirectToAction("SurveyContinue", "../Product", new
            {

src/App/Views/Oferta/DatosPersonales.cshtml
@model App.Models.VendorViewModel
@{
    ViewBag.Title = "Datos Personales";
}


<div class="container sat-spacing">
    <div class="row">
        <div class="sat-titlesOpening col-xs-12">
            <h2>
                @ViewBag.Title
            </h2>
        </div>
    </div>

<form action="DatosPersonales" method="post" enctype="multipart/form-data">
    <div class="container sat-Ds sat-datos">
       
        <div class="row">
            <div class="col-md-10 col-md-offset-1 alert alert-maker">
                @if (ViewBag.Msg != null){
                    <div class="alert alert-success">
                        @ViewBag.Msg
                    </div>
                }
                @Html.HiddenFor(x => x.Id)
                @Html.HiddenFor(x => x.CompanyId)
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#user">Datos del usuario</a></li>
                    <li><a data-toggle="tab" href="#company">Datos de la empresa</a></li>
                </ul>
                <div class="tab-content">
                    <div id="user" class="tab-pane fade in active">
                        <div class="row col-lg-12" style="margin-top:20px">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.FirstName, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.LastName, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "col-md-4 control-gabel text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @readonly="true" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="company" class="tab-pane fade">
                        <div class="row col-lg-12" style="margin-top:20px">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyName, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyDescription, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextAreaFor(m => m.CompanyDescription, new { @class = "form-control", @rows = 3 })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyWebSite, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.CompanyWebSite, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyCity, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.CompanyCity, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyAddress, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.CompanyAddress, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyPostalCode, new { @class = "col-md-4 control-label text-left-important" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.CompanyPostalCode, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyBranchOfficesIn, new { @class = "col-md-7 control-label text-left-important" })
                                    <div class="col-md-5">
                                        @Html.TextBoxFor(m => m.CompanyBranchOfficesIn, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyFiscalStartDate, new { @class = "col-md-7 control-label text-left-important" })
                                    <div class="col-md-5">
                                        @Html.DropDownListFor(m => m.CompanyFiscalStartDate, Model.Months, "Seleccione...", new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyFiscalEndDate, new { @class = "col-md-7 control-label text-left-important" })
                                    <div class="col-md-5">
                                        @Html.DropDownListFor(m => m.CompanyFiscalEndDate, Model.Months, "Seleccione...", new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyPeopleInCompany, new { @class = "col-md-7 control-label text-left-important" })
                                    <div class="col-md-5">
                                        @Html.TextBoxFor(m => m.CompanyPeopleInCompany, new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-primary pull-right" value="Guardar cambios" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>

src/App/Views/Oferta/Home.cshtml
@{
    ViewBag.Title = "AdminHome";
}

<div class="homeProveedores">
<div class="homeProveedoresContaine">
<div class="row">
    <div class="col-md-offset-3 col-md-6 ">
            <h1 class="text-center">Bienvenido al área de administración para los proveedores.</h1>
    </div>
</div>
<div class="container">
    <div class="row service">
        <div class="col-md-4 ">
            <div class="sat-services sat-Ds">
            <a class="" href="/Product/Category"><h2>Registrar producto o servicio &raquo;</h2></a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="sat-services sat-Ds">
            <a class="" href="/Oferta/listProducts"><h2>Ver mis productos y servicios &raquo;</h2></a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="sat-services sat-Ds">
            <a class="" href="/Contact"><h2>Datos personales  &raquo;</h2></a>
            </div>
        </div>
    </div>
</div>
</div>
</div>

src/App/Views/Oferta/ProductList.cshtml
@{
    ViewBag.Title = "Mis productos y servicios";
}

<div class="container sat-spacing">
    <div class="row">
        <div class="sat-titlesOpening col-xs-12">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
    <div class="row sat-Ds">
    <div class="table-responsive col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Categoría</th>
                    <th>Nombre</th>
                    <th>Version</th>
                    <th>Descripcion</th>
                    <th>Sitio web</th>
                    <th>Estado</th>
                    <th style="min-width: 151px;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.surveyCompletionParents != null)
                {
                    foreach (var survey in ViewBag.surveyCompletionParents)
                    {
                        <tr>
                            <td>@survey.Category.Name</td>
                            <td>@survey.Product.Name</td>
                            <td>@survey.Product.Version</td>
                            <td>@survey.Product.Description</td>
                            <td>@survey.Product.WebSite</td>
                            <td>@survey.Status</td>
                            <td>
                                @if(true) //(ViewBag.outdatedSurveys[survey.Id])
                                {
                                <a href="/Oferta/UpdateProduct/@survey.Id" class="btn btn-info" role="button">Modificar</a>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    </div>
</div>

src/App/Views/Oferta/UpdateSurvey.cshtml
@model App.Models.Survey.SurveyUpdateViewModel
@{
    ViewBag.Title = "Actualizar Encuesta";
}

<form method="post" class="form-horizontal" role="form">
<div class="container sat-spacing">
    <div class="row">
        <div class="sat-titlesOpening col-xs-12">
            <h2>@ViewBag.Title</h2>
            <h4 class="title-type">Actualizar datos</h4>
        </div>
        <ol class="breadcrumb sat-breadcrumb" style="background-color: white;">
            <li>Rubro</li>
            <li class="active">Registro</li>
            <li>Fin</li>
        </ol>
    </div>

    @Html.HiddenFor(x => x.CompanyId)

    <div class="container sat-Ds">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                @{int i = 0;  }
                <div>
                    <h4 class="text-center">
                        @ViewBag.survey.CategoryObj.Name
                    </h4>
                    <input type="hidden" name="ProductId" value="@ViewBag.survey.Parent.Id">
                    <input type="hidden" name="SurveyCompletionId" value="@ViewBag.survey.Id">
                    @foreach (var question in Model.SurveyQuestionDTOs)
                    {
                        if (!question.Old)
                        {
                            <input type="hidden" name="surveyCompletionDTOs[@i].QuestionId" value="@question.QuestionId">
                            <input type="hidden" name="surveyCompletionDTOs[@i].Question" value="@question.Question">
                            <input type="hidden" name="surveyCompletionDTOs[@i].SurveyId" value="@ViewBag.survey.SurveyId">
                            Html.RenderAction("Question", "OfertaSurvey", new { id = question.QuestionId, identifier = i, surveyCompletionId = ViewBag.survey.Id, @class = "col-lg-12" });

                            i++;
                        }
                    }

                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-12">
                <input type="submit" class="btn btn-info pull-right" value="Actualizar" name="action:Save" />
            </div>
        </div>
    </div>
</div>
</form>
@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <script src="@Url.Content("~/Scripts/chosen.jquery.js")" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.chosen-select').chosen();
            $('.chosen-select-deselect').chosen({ allow_single_deselect: true });
        });
    </script>
}