src/App/Models/Admin/SurveyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace App.Models.Admin
{
    public class SurveyViewModel
    {
        [Required]
        [Display(Name = "Evaluación")]
        public HttpPostedFileBase SurveyFile { get; set; }

        public string BusinessError { get; set; }
    }
}

src/App/Models/Oferta/RegisterViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace App.Models.Oferta
{
    public class RegisterViewModel
    {
        public RegisterViewModel() 
        {
            this.Countries = new List<SelectListItem>
            {
                new SelectListItem { Text = "Argentina", Value = "Argentina" },
                new SelectListItem { Text = "Bolivia", Value = "Bolivia" },
                new SelectListItem { Text = "Brasil", Value = "Brasil" },
                new SelectListItem { Text = "Canadá", Value = "Canadá" },
                new SelectListItem { Text = "Chile", Value = "Chile" },
                new SelectListItem { Text = "Colombia", Value = "Colombia" },
                new SelectListItem { Text = "Costa Rica", Value = "Costa Rica" },
                new SelectListItem { Text = "Cuba", Value = "Cuba" },
                new SelectListItem { Text = "Ecuador", Value = "Ecuador" },
                new SelectListItem { Text = "EEEUU", Value = "EEEUU" },
                new SelectListItem { Text = "El Salvador", Value = "El Salvador" },
                new SelectListItem { Text = "España", Value = "España" },
                new SelectListItem { Text = "Honduras", Value = "Honduras" },
                new SelectListItem { Text = "México", Value = "México" },
                new SelectListItem { Text = "Nicaragua", Value = "Nicaragua" },
                new SelectListItem { Text = "Panamá", Value = "Panamá" },
                new SelectListItem { Text = "Paraguay", Value = "Paraguay" },
                new SelectListItem { Text = "Perú", Value = "Perú" },
                new SelectListItem { Text = "Uruguay", Value = "Uruguay" },
                new SelectListItem { Text = "Venezuela", Value = "Venezuela" },
                new SelectListItem { Text = "Otro", Value = "Otro" }
            };

            this.Months = new List<SelectListItem>
            {
                new SelectListItem { Text = "Enero", Value = "Enero" },
                new SelectListItem { Text = "Febrero", Value = "Febrero" },
                new SelectListItem { Text = "Marzo", Value = "Marzo" },
                new SelectListItem { Text = "Abril", Value = "Abril" },
                new SelectListItem { Text = "Mayo", Value = "Mayo" },
                new SelectListItem { Text = "Junio", Value = "Junio" },
                new SelectListItem { Text = "Julio", Value = "Julio" },
                new SelectListItem { Text = "Agosto", Value = "Agosto" },
                new SelectListItem { Text = "Septiembre", Value = "Septiembre" },
                new SelectListItem { Text = "Octubre", Value = "Octubre" },
                new SelectListItem { Text = "Noviembre", Value = "Noviembre" },
                new SelectListItem { Text = "Diciembre", Value = "Diciembre" },
            };
        }

        public int CategoryId { get; set; }
        public int SurveyCompletionId { get; set; }

        //[Required]
        [Display(Name = "Nombre")]
        public string CompanyName { get; set; }
        
        //[Required]
        [Display(Name = "Descripción")]
        public string CompanyDescription { get; set; }

        //[Required]
        [Display(Name = "Sitio web")]
        public string CompanyWebSite { get; set; }

        public List<SelectListItem> Countries { get; set; }

        //[Required]
        [Display(Name = "País")]
        public string CompanyCountry { get; set; }

        //[Required]
        [Display(Name = "Ciudad")]
        public string CompanyCity { get; set; }

        //[Required]
        [Display(Name = "Dirección")]
        public string CompanyAddress { get; set; }

        [Display(Name = "Código Postal")]
        public string CompanyPostalCode { get; set; }

        [Display(Name = "Sucursales en")]
        public string CompanyBranchOfficesIn { get; set; }

        public List<SelectListItem> Months { get; set; }

        //[Required]
        [Display(Name = "Mes de inicio del año fiscal")]
        public string CompanyFiscalStartDate { get; set; }

        //[Required]
        [Display(Name = "Mes de cierre del año fiscal")]
        public string CompanyFiscalEndDate { get; set; }

        //[Required]
        [Display(Name = "Personal total de la empresa")]
        public int CompanyPeopleInCompany { get; set; }

        [Display(Name = "Logo")]
        public HttpPostedFileBase CompanyLogo { get; set; }

        public string CompanyLogoFileName { get; set; }

        //[Required]
        [Display(Name = "Nombre")]
        public string ProductName { get; set; }

        [Display(Name = "Version")]
        public string ProductVersion { get; set; }

        //[Required]
        [Display(Name = "Descripción")]
        public string ProductDescription { get; set; }

        [Display(Name = "Sitio web")]
        public string ProductWebSite { get; set; }

        //[Required]
        [Display(Name = "Nombre y Apellido")]
        public string ComercialContactFullName { get; set; }

        //[Required]
        [Display(Name = "Cargo / Función")]
        public string ComercialContactPosition { get; set; }

        //[Required]
        [Display(Name = "Teléfono")]
        public string ComercialContactPhone { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        public string ComercialContactEmail { get; set; }

        [Display(Name = "Nombre y Apellido")]
        public string ProductContactFullName { get; set; }

        [Display(Name = "Cargo / Función")]
        public string ProductContactPosition { get; set; }

        [Display(Name = "Teléfono")]
        public string ProductContactPhone { get; set; }

        [EmailAddress]
        [Display(Name = "Email")]
        public string ProductContactEmail { get; set; }
    }
}

src/App/Models/Oferta/Survey/CategoryViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace App.Models.Oferta.Survey
{
    public class CategoryViewModel
    {
        public CategoryViewModel() 
        {
            this.Categories = new List<System.Web.Mvc.SelectListItem>();
        }

        [Required(ErrorMessage = "Por favor seleccione el rubro")]
        [Display(Name = "Rubro")]
        public string Category { get; set; }

        public List<System.Web.Mvc.SelectListItem> Categories { get; set; }
    }
}

src/App/Models/Survey/CategoryViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace App.Models.Survey
{
    public class CategoryViewModel
    {
        public CategoryViewModel()
        {
            this.Categories = new List<System.Web.Mvc.SelectListItem>();
        }

        [Display( Name = "Rubro" )]
        [Required]
        public string Category { get; set; }

        public List<System.Web.Mvc.SelectListItem> Categories { get; set; }
        public string SelectedCategory { get; internal set; }
    }
}

src/App/Controllers/Demanda/SurveyController.cs
using App.Attribute;
using App.DTO;
using App.Model.User;
using App.Models.Demanda.Continue.Email;
using App.Models.Survey;
using App.Service.Demanda;
using App.Services.Demanda.Continue;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Model.Context;
using Model.Customer;
using Model.Model.EvaluationReport;
using Model.SurveyCompletion;
using Model.Suvery;
using Services;
using Services.Service.EmailService;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace App.Controllers.Demanda
{
    public class SurveyController : Controller
    {
        private ModelContext modelContext;
        private UserManager<ApplicationUser> userManager;
        private RoleManager<ApplicationRole> roleManager;
        private SurveyCompletionByDemandEmailService surveyCompletionByDemandEmailService;
        private PdfService pdfService;
        private RankingService rankingService;
        private SurveyService surveyService;
        private EvaluationService evaluationService;
        private SendEmailToContinueService sendEmailToContinueService;

        public SurveyController()
        {
            this.modelContext = new ModelContext();

            var userStore = new UserStore<ApplicationUser>(this.modelContext);
            var roleStore = new RoleStore<ApplicationRole>(this.modelContext);

            this.userManager = new UserManager<ApplicationUser>(userStore);
            this.roleManager = new RoleManager<ApplicationRole>(roleStore);

            this.surveyCompletionByDemandEmailService = new SurveyCompletionByDemandEmailService();
            this.pdfService = new PdfService();
            this.rankingService = new RankingService();
            this.surveyService = new SurveyService();
            this.evaluationService = new EvaluationService();
            this.sendEmailToContinueService = new SendEmailToContinueService();
        }

        public ActionResult Index(int Category, string subCategories)
        {
            List<SurveyDTO> surveys = new List<SurveyDTO>();

            List<int> subcategories_Ids = new List<int>();

            foreach (string s in subCategories.Split(','))
                if (s != "")
                    subcategories_Ids.Add(int.Parse(s));

            renderSubCategory(Category, surveys, subcategories_Ids);

            var model = new SurveyViewModel
            {
                SurveyDTOs = surveys,
                CategoryId = Category,
                SurveyId = surveys.Where(x => x.CategoryId == Category).FirstOrDefault().SurveyId
            };

            return View("~/Views/Demanda/Survey.cshtml", model);
        }

        private void renderSubCategory(int CategoryId, List<SurveyDTO> surveys, List<int> subcategories_Ids)
        {
            //primero me agrego a mi mismo
            var survey = this.modelContext
                .Surveys
                .Include("Category")
                .Include("Questions")
                .Where(x => x.Category.Id == CategoryId)
                .OrderByDescending(x => x.Id)
                .FirstOrDefault();

            var questions = survey.Questions
                .Select(question => new SurveyQuestionDTO
                {
                    QuestionId = question.Id,
                    Question = question.DemandQuestion,
                    Required = question.DemandRequired,
                    Old = question.Old
                })
                .ToList();

            ViewBag.QuestionCount += questions.Count();

            SurveyDTO surveyDTO = new DTO.SurveyDTO()
            {
                CategoryId = CategoryId,
                CategoryName = survey.Category.getFullName(),
                SurveyQuestionDTOs = questions,
                SurveyId = survey.Id
            };

            surveys.Add(surveyDTO);

            //busco las subSurveys de las subcategorias hijas y que estèn incluidas en el array de seleccioadas
            var subSurveys = this.modelContext
                .Surveys
                .Include("Category")
                .Include("Questions")
                .Where(x => x.Category.parentCategory.Id == CategoryId && subcategories_Ids.Contains(x.Category.Id)).ToList();

            foreach (Survey subSurvey in subSurveys)
            {
                renderSubCategory(subSurvey.Category.Id, surveys, subcategories_Ids);
            }
        }

        public ActionResult Question(int id, int identifier)
        {
            var question = this.modelContext
                .Questions
                .Include("AnswerType")
                .Include("Answers")
                .Where(x => x.Id == id)
                .FirstOrDefault();

            var model = new QuestionViewModel
            {
                Identifier = identifier,
                Id = question.Id,
                Question = question.DemandQuestion,
                Required = question.DemandRequired,
                Type = question.AnswerType.Name,
                Answers = question.Answers.Select(answer => new AnswerDTO
                {
                    Id = answer.Id,
                    Answer = answer.DemandAnswer
                })
                    .ToList()
            };

            var view = "~/Views/Survey/Question/" + question.AnswerType.Name + ".cshtml";

            return PartialView(view, model);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Save")]
        public ActionResult Save(SurveyViewModel model, string Argument)
        {
            string sourceQueryStringKey = ConfigurationManager.AppSettings["UTMSource"];
            if (Session[sourceQueryStringKey] != null)
            {
                model.Source = Session[sourceQueryStringKey].ToString();
                Session[sourceQueryStringKey] = null;
            }
            var surveyCompletionParent = this.evaluationService.Save(model, false, User.Identity.GetUserId());

            var surveyCompletion = this.modelContext
                .SurveyCompletionParent
                .FirstOrDefault(x => x.Id == surveyCompletionParent.Id);

            var customer = this.modelContext
                .Customers
                .Where(x => x.Email == model.Email)
                .FirstOrDefault();

            if (customer != null)
            {
                surveyCompletion.Customer = customer;
                this.modelContext.SaveChanges();

                return RedirectToAction("Thanks", "../Evaluation", new { surveyCompletionId = surveyCompletionParent.Id });
            }

            return RedirectToAction("Registration", "../Evaluation", new { surveyCompletionParentId = surveyCompletionParent.Id });
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "SaveParcial")]
        public ActionResult SaveParcial(SurveyViewModel model, string Argument)
        {
            string sourceQueryStringKey = ConfigurationManager.AppSettings["UTMSource"];
            if (Session[sourceQueryStringKey] != null)
            {
                model.Source = Session[sourceQueryStringKey].ToString();
                Session[sourceQueryStringKey] = null;
            }
            var surveyCompletionParent = this.evaluationService.Save(model, true, User.Identity.GetUserId());

            //Get email body
            var link = this.sendEmailToContinueService.GetLink(surveyCompletionParent);
            var body = this.RenderRazorViewToString("~/Views/Demanda/Continue/Email/Continue.cshtml", new ContinueViewModel { Link = link });

            //Generate PDF
            var template = this.RenderRazorViewToString("~/Views/Demanda/Email/EvaluationTemplate.cshtml", surveyCompletionParent);
            var fileName = this.pdfService.GetEvaluationFileName(surveyCompletionParent.Id);
            var pdfFullName = this.pdfService.Generate(surveyCompletionParent.Id, template, fileName);

            this.sendEmailToContinueService.Send(surveyCompletionParent.Email, body, pdfFullName);

            return RedirectToAction("ThanksPartial", "../Product/Evaluation");
        }

        private SurveyCompletionParent InsertSurveyCompletion(SurveyViewModel model, bool partial)
        {
            var category = this.modelContext
                .Categories
                .Where(x => x.Id == model.CategoryId)
                .FirstOrDefault();

            var role = this.roleManager.FindByName("DEMANDA");

            var surveyCompletionParent = new SurveyCompletionParent
            {
                Product = null,
                Role = role,
                Status = "Aprobado",
                PartialSave = partial,
                Category = category,
                Email = model.Email,
                PartialSaveKey = Guid.NewGuid().ToString()
            };

            foreach (var survey in model.SurveyDTOs)
            {
                var surveyCompletion = new SurveyCompletion
                {
                    SurveyId = survey.SurveyId,
                    CategoryId = survey.CategoryId,
                    Category = survey.CategoryName,
                    Email = model.Email,
                    Role = role,
                    Parent = surveyCompletionParent,
                    PartialSave = partial
                };

                var surveyQuestions = this.modelContext
                        .Questions
                        .Include("Answers")
                        .Where(x => x.Survey.Id == survey.SurveyId)
                        .ToList();

                foreach (var question in model.surveyCompletionDTOs)
                {
                    var answers = new List<SurveyCompletionAnswer>();
                    if (question.SurveyId == survey.SurveyId)
                    {
                        if (question.Answers != null)
                        {

src/App/Views/Demanda/Survey.cshtml
@model App.Models.Survey.SurveyViewModel
@{
    ViewBag.Title = "Obtener Recomendación";
}

<form action="/Evaluation/Save" method="post" class="" role="form" novalidate="novalidate">
    @Html.AntiForgeryToken()
    <div class="container sat-survey">

        @Html.HiddenFor( x => x.CategoryId ) @Html.HiddenFor( x => x.SurveyId ) @Html.ValidationMessage( "Question" )
        <div class="row sat-mailSurvey">
            <div class="col-md-offset-3 col-md-6">
                <div class="form-group alert alert-maker">
                    <label>Por favor ingrese su email para que podamos enviarle los resultados</label>
                    <input type="email" class="form-control" name="email" id="email" required value="@Model.Email" /> @Html.ValidationMessage( "email" )
                    <a class="sat-btn" href="#comienzo">Comenzar</a>
                </div>
            </div>
        </div>
        <a name="comienzo"></a>
        <div class="row">
            <div class="sat-titlesOpening col-xs-12">
                <h2>@ViewBag.Title</h2>
                <h3 class="title-type">¿Qué esperás de tu producto o servicio?</h3>
            </div>
            <ol class="breadcrumb sat-breadcrumb">
                <li>Rubro</li>
                <li class="active">Evaluaci&oacute;n</li>
                <li>Registro</li>
                <li>Fin</li>
            </ol>
        </div>
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <h4 class="title-type" style="margin-top: 10px;">
                    Inicio de Evaluaci&oacute;n
                </h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-3 col-md-6 sat-survey">
                @{int i = 0; int j = 0; } @foreach( var survey in Model.SurveyDTOs )
                {
                    <h4 class="sat-titleSurvey">
                        @survey.CategoryName
                    </h4>
                    <input type="hidden" name="SurveyDTOs[@j].SurveyId" value="@survey.SurveyId">
                    <input type="hidden" name="SurveyDTOs[@j].CategoryId" value="@survey.CategoryId"> foreach( var question in survey.SurveyQuestionDTOs )
                    {
                        if( !question.Old )
                        {
                            <input type="hidden" name="surveyCompletionDTOs[@i].QuestionId" value="@question.QuestionId">
                            <input type="hidden" name="surveyCompletionDTOs[@i].Question" value="@question.Question">
                            <input type="hidden" name="surveyCompletionDTOs[@i].SurveyId" value="@survey.SurveyId">Html.RenderAction( "Question", "Survey", new { id = question.QuestionId, identifier = i, surveyCompletionId = Model.SurveyCompletionId } ); i++;
                        }
                    }
                    j++;
                }
            </div>
        </div>
        <div class="btn-survey-shadow">
            <div id="btn-survey" class="row-display-none row">
                <div class="col-md-12 text-center">
                    <h4>Progreso</h4>
                    <div class="progress-container">
                        <div class="progress-bar" id="myBar"></div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8 text-center">
                            <input id="btn-guardar" type="submit" class="btn btn-secondary sat-btn-guardar" name="action:SaveParcial" value="Guardar y continuar luego" />
                            <input id="btn-finalizar" type="submit" class="btn btn-primary sat-btn-finalizar" name="action:Save" value="Finalizar" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script>

// Barra de progreso
jQuery(function($) {

    var $nav = $('#btn-survey');
    var $win = $(window);
    var winH = $win.height(); // Get the window height.

	var d = document.documentElement;
	var offset = d.scrollTop + window.innerHeight;
	var height = d.offsetHeight;

    $win.on("scroll", function () {
        if ($(this).scrollTop() >= 0.4 * winH ) {
            $nav.removeClass( "row-display-none" ).addClass("row-fixed-bottom");
        } else {
            $nav.removeClass("row-fixed-bottom");
        }

		if ($(window).scrollTop() + $(window).height() === $(document).height()) {
			$nav.removeClass("row-fixed-bottom").addClass("row-display");
		}
		else{
			$nav.removeClass("row-display").addClass("row-fixed-bottom");
		}

    }).on("resize", function(){ // If the user resizes the window
       winH = $(this).height(); // you'll need the new height value

    })
});
</script>

<script>

        window.onscroll = function() {myFunction()};

        function myFunction() {
			var winScroll =  ($(window).scrollTop()) - $(".row.sat-mailSurvey").height(); //document.body.scrollTop || document.documentElement.scrollTop;
			var height = document.documentElement.scrollHeight - document.documentElement.clientHeight - $(".row.sat-mailSurvey").height();
			var scrolled = (winScroll / height) * 100;
			console.log(scrolled+"%");
			document.getElementById("myBar").style.width = scrolled + "%";
        }
</script>

@section Scripts {
    @Scripts.Render( "~/bundles/jqueryval" )
}